services:
  mailserver:
    image: ghcr.io/docker-mailserver/docker-mailserver:latest
    container_name: TPI-4K4
    hostname: mail
    domainname: local.test
    ports:
      - "1025:25" #SMTP
      - "1587:587" #SUBMISSION
      - "1143:143" #IMAP
    volumes:
      - mail-data:/var/mail/
      - mail-state:/var/mail-state/
      - mail-logs:/var/log/mail/
      - ./docker-data/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    environment:
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
      - SSL_TYPE=self-signed
      - SMTP_ONLY=0
      - PERMIT_DOCKER=network
    cap_add:
      - NET_ADMIN
volumes:
  mail-data:
  mail-state:
  mail-logs: